
[terminal.shell]
program = "/usr/bin/env"
args = ["tmux"]

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.normal]
family = "MapleMono NF"
style = "Regular"

[font.bold]
family = "MapleMono NF"
style = "Bold"

[font.italic]
family = "MapleMono NF"
style = "Italic"

[font.bold_italic]
family = "MapleMono NF"
style = "Bold Italic"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/keybinds.toml"
]

[terminal]
